name: Automatic Deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Welcome
        run: echo Start deploying SenSwap Home
      - name: Build Dockerfile
        run: |
          sed -i 's/__ENV__/prod/g' Dockerfile
          cat Dockerfile
      - name: Build docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tuphanson/senswap-home-mainnet
          tags: latest
      - name: Run docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_MAINNET }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATEKEY_MAINNET }}
          script: |
            sudo docker stop home
            sudo docker rm home
            sudo docker pull tuphanson/senswap-home-mainnet
            sudo docker run -d -p 80:80 --name home tuphanson/senswap-home-mainnet
            sudo docker image prune -a -f
